# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:----/ui_testingSoftware.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1324, 948)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 589, 1181, 190))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_Toplam_Bubble_Num = QtWidgets.QLabel(self.layoutWidget)
        self.label_Toplam_Bubble_Num.setObjectName("label_Toplam_Bubble_Num")
        self.verticalLayout_4.addWidget(self.label_Toplam_Bubble_Num)
        self.label_Toplam_Bubble_Alan = QtWidgets.QLabel(self.layoutWidget)
        self.label_Toplam_Bubble_Alan.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_Toplam_Bubble_Alan.setObjectName("label_Toplam_Bubble_Alan")
        self.verticalLayout_4.addWidget(self.label_Toplam_Bubble_Alan)
        self.pushButtonStart = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonStart.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.pushButtonStart.setObjectName("pushButtonStart")
        self.verticalLayout_4.addWidget(self.pushButtonStart)
        self.pushButtonSave = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonSave.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.verticalLayout_4.addWidget(self.pushButtonSave)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 50, 601, 541))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonSelectFile = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButtonSelectFile.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.pushButtonSelectFile.setObjectName("pushButtonSelectFile")
        self.verticalLayout.addWidget(self.pushButtonSelectFile)
        self.label_Img_Photo_1 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_Img_Photo_1.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 139, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label_Img_Photo_1.setObjectName("label_Img_Photo_1")
        self.verticalLayout.addWidget(self.label_Img_Photo_1)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(641, 51, 581, 541))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButtonRead = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButtonRead.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.pushButtonRead.setObjectName("pushButtonRead")
        self.verticalLayout_2.addWidget(self.pushButtonRead)
        self.label_Image_photo_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_Image_photo_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 139, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label_Image_photo_2.setObjectName("label_Image_photo_2")
        self.verticalLayout_2.addWidget(self.label_Image_photo_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1324, 26))
        self.menubar.setObjectName("menubar")
        self.menuHome = QtWidgets.QMenu(self.menubar)
        self.menuHome.setObjectName("menuHome")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuHome.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Toplam_Bubble_Num.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Toplam Bubble Sayısı :</span></p></body></html>"))
        self.label_Toplam_Bubble_Alan.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:400;\">Toplam Bubble Alanı  :</span></p></body></html>"))
        self.pushButtonStart.setText(_translate("MainWindow", "START"))
        self.pushButtonSave.setText(_translate("MainWindow", "SAVE"))
        self.pushButtonSelectFile.setText(_translate("MainWindow", "SELECT FILE"))
        self.label_Img_Photo_1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">NO PROCESSING IMAGE</span></p></body></html>"))
        self.pushButtonRead.setText(_translate("MainWindow", "READ"))
        self.label_Image_photo_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">IMAGE RESULT</span></p></body></html>"))
        self.menuHome.setTitle(_translate("MainWindow", "Home"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
